In [85]:
# DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table, and it is one of the most commonly used data structures in pandas for data manipulation and analysis.

# Creating Your First DataFrame
import pandas as pd

data = {
    "Name": ["Laksh", "Aryan", "Parth"],
    "Age": [20, 21, 22],
    "Marks": [90, 85, 95]
}
df = pd.DataFrame(data)
print(df)

print()
print("Understanding Output")
print("""| Part             | Meaning     |
| ---------------- | ----------- |
| 0,1,2            | Row indexes |
| Name, Age, Marks | Columns     |
| Laksh, 20, 90    | Data        |
""")

    Name  Age  Marks
0  Laksh   20     90
1  Aryan   21     85
2  Parth   22     95

Understanding Output
| Part             | Meaning     |
| ---------------- | ----------- |
| 0,1,2            | Row indexes |
| Name, Age, Marks | Columns     |
| Laksh, 20, 90    | Data        |

In [86]:
# Checking the type of df
print(type(df))

<class 'pandas.DataFrame'>

In [87]:
# DataFrame Attributes

print("DataFrame Attributes:\n")
# These attributes provide information about the structure and content of the DataFrame.

print(f"Shape: {df.shape}\n")
# The shape attribute returns a tuple representing the dimensions of the DataFrame (number of rows, number of columns).

print(f"Columns: {df.columns}\n")
# The columns attribute returns an Index object containing the column labels of the DataFrame.  

print(f"Index: {df.index}\n")
# The index attribute returns an Index object containing the row labels of the DataFrame. By default, it is a RangeIndex starting from 0.

print(f"Data Types:\n{df.dtypes}\n")
# The dtypes attribute returns a Series with the data type of each column in the DataFrame.

DataFrame Attributes:

Shape: (3, 3)

Columns: Index(['Name', 'Age', 'Marks'], dtype='str')

Index: RangeIndex(start=0, stop=3, step=1)

Data Types:
Name       str
Age      int64
Marks    int64
dtype: object

In [88]:
# Viewing Data

data1 = {
    "Name": ["Laksh", "Aryan", "Parth","Rohit","Rahul","Suresh"],
    "Age": [20, 21, 22, 23, 24, 25],
    "Marks": [90, 85, 95, 88, 92, 87]
}
df = pd.DataFrame(data1)
print(df)

print("Viewing Data:\n")
# These methods allow you to view the contents of the DataFrame in different ways.

print("Head of the DataFrame:")
print(df.head())
# The head() method returns the first n rows of the DataFrame (default is 5). It is useful for quickly inspecting the data.

print("\nTail of the DataFrame:")
print(df.tail())
# The tail() method returns the last n rows of the DataFrame (default is 5). It is useful for inspecting the end of the data.

print("\nSample of the DataFrame:")
print(df.sample(3))
# The sample() method returns a random sample of n rows from the DataFrame. It is useful for getting a quick look at the data without looking at the entire DataFrame.

     Name  Age  Marks
0   Laksh   20     90
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87
Viewing Data:

Head of the DataFrame:
    Name  Age  Marks
0  Laksh   20     90
1  Aryan   21     85
2  Parth   22     95
3  Rohit   23     88
4  Rahul   24     92

Tail of the DataFrame:
     Name  Age  Marks
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87

Sample of the DataFrame:
    Name  Age  Marks
3  Rohit   23     88
1  Aryan   21     85
2  Parth   22     95

In [89]:
# Selecting Columns
print("Selecting Columns:\n")
# You can select columns from a DataFrame using the column labels.

print("Selecting the 'Name' column:")
print(df["Name"])
# You can select a single column by using its label in square brackets. This returns a Series.  

print("\nSelecting the 'Name' and 'Marks' columns:")
print(df[["Name", "Marks"]])
# You can select multiple columns by passing a list of column labels in square brackets. This returns a DataFrame containing only the specified columns.

# Adding a new column
print("\nAdding a new column 'Grade':")
df["Grade"] = ["A", "B", "C", "B", "A", "C"]
print(df)  
# You can add a new column to the DataFrame by assigning a list of values to a new column label. The length of the list must match the number of rows in the DataFrame.

# Deleting a column
print("\nDeleting the 'Grade' column:")
del df["Grade"]
print(df)
# You can delete a column from the DataFrame using the del statement followed by the column label in square brackets. This removes the column from the DataFrame permanently.

Selecting Columns:

Selecting the 'Name' column:
0     Laksh
1     Aryan
2     Parth
3     Rohit
4     Rahul
5    Suresh
Name: Name, dtype: str

Selecting the 'Name' and 'Marks' columns:
     Name  Marks
0   Laksh     90
1   Aryan     85
2   Parth     95
3   Rohit     88
4   Rahul     92
5  Suresh     87

Adding a new column 'Grade':
     Name  Age  Marks Grade
0   Laksh   20     90     A
1   Aryan   21     85     B
2   Parth   22     95     C
3   Rohit   23     88     B
4   Rahul   24     92     A
5  Suresh   25     87     C

Deleting the 'Grade' column:
     Name  Age  Marks
0   Laksh   20     90
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87

In [90]:
# Accessing Rows
print("\nAccessing Rows:\n")
# You can access rows in a DataFrame using the loc and iloc indexers.

# loc[] -> Label Based Indexing
print("Accessing the first row using loc:")
print(df.loc[0])
# The loc indexer allows you to access rows by their label. In this case, we are accessing the first row using its index label 0.

# iloc[] -> Integer Position Based Indexing
print("\nAccessing the third row using iloc:")
print(df.iloc[2])
# The iloc indexer allows you to access rows by their integer position. In this case, we are accessing the third row using its integer position 2.

# Add a new row at index position 6
print("\nAdding a new row at index 6:")
new_row = {"Name": "Ankit", "Age": 26, "Marks": 89}
df.loc[6] = new_row
print(df)
# Using loc with index 6 inserts/updates that row label directly without using deprecated append().

# Removing Rows
print("\nRemoving the last row:")
df = df.drop(6)
print(df)
# You can remove rows from the DataFrame using drop() by specifying the index label to remove.

Accessing Rows:

Accessing the first row using loc:
Name     Laksh
Age         20
Marks       90
Name: 0, dtype: object

Accessing the third row using iloc:
Name     Parth
Age         22
Marks       95
Name: 2, dtype: object

Adding a new row at index 6:
     Name  Age  Marks
0   Laksh   20     90
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87
6   Ankit   26     89

Removing the last row:
     Name  Age  Marks
0   Laksh   20     90
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87

In [91]:
# Filtering Data

# You can filter the DataFrame based on conditions. For example, to filter rows where the "Marks" column is greater than or equal to 90:
print(df[df["Marks"] >= 90])
print()
# Multiple conditions can be combined using & (and) and | (or) operators. For example, to filter rows where "Marks" is greater than or equal to 90 and "Age" is less than 25:
print(df[(df["Marks"] >= 80) & (df["Age"] < 25)])

    Name  Age  Marks
0  Laksh   20     90
2  Parth   22     95
4  Rahul   24     92

    Name  Age  Marks
0  Laksh   20     90
1  Aryan   21     85
2  Parth   22     95
3  Rohit   23     88
4  Rahul   24     92

In [92]:
# Sorting Data
# You can sort the DataFrame by one or more columns using the sort_values() method. For example, to sort the DataFrame by the "Marks" column in descending order:
print("\nSorting the DataFrame by 'Age' in Ascending order:")        
print(df.sort_values("Age")) #Ascending

print("\nSorting the DataFrame by 'Age' in Desecending order:")  
print(df.sort_values("Age", ascending=False)) # Descending

Sorting the DataFrame by 'Age' in Ascending order:
     Name  Age  Marks
0   Laksh   20     90
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87

Sorting the DataFrame by 'Age' in Desecending order:
     Name  Age  Marks
5  Suresh   25     87
4   Rahul   24     92
3   Rohit   23     88
2   Parth   22     95
1   Aryan   21     85
0   Laksh   20     90

In [93]:
# Basic DataFrame Functions
print("\nBasic DataFrame Functions:")
print(df.info())

Basic DataFrame Functions:
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 308.0 bytes
None

In [94]:
# Describe the DataFrame Function

print(df.describe())

# The describe() method generates descriptive statistics of the DataFrame, including count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum for each numeric column. This is useful for getting a quick overview of the distribution and central tendency of the data.

             Age      Marks
count   6.000000   6.000000
mean   22.500000  89.500000
std     1.870829   3.619392
min    20.000000  85.000000
25%    21.250000  87.250000
50%    22.500000  89.000000
75%    23.750000  91.500000
max    25.000000  95.000000

In [95]:
# Renaming Columns

df.rename(columns={"Marks": "Score"}, inplace=True)
print(df)

     Name  Age  Score
0   Laksh   20     90
1   Aryan   21     85
2   Parth   22     95
3   Rohit   23     88
4   Rahul   24     92
5  Suresh   25     87

##### Changing Index: changing index allows you to set a specific column as the index of the DataFrame, which can be useful for easier data access and manipulation based on that column.
```
df.set_index("Name", inplace=True)
```

##### Reset Index: resetting the index allows you to revert the DataFrame back to its default integer index, which can be useful if you want to remove a custom index or if you want to use the original index for some reason.
```
df.reset_index(inplace=True)
```

In [ ]:
# Missing Values: Missing values can occur in a DataFrame when data is not available for certain entries. They are typically represented as NaN (Not a Number) in pandas. Handling missing values is an important aspect of data cleaning and analysis.

data2 = {
    "Name": ["Laksh", "Aryan", "Parth", "Rohit", "Rahul", "Suresh"],
    "Age": [20, 21, 22, 23, 24, 25],
    "Marks": [90, 85, None, 88, None, 87]
}
df1 = pd.DataFrame(data2)
print(df1)
print("\nDataFrame with Missing Values:")
# Checking for Missing Values: You can check for missing values in a DataFrame using the isnull() method, which returns a DataFrame of the same shape with boolean values indicating whether each entry is null (True) or not (False).
print(df1.isnull()) 

print("\nCount of Missing Values in Each Column:")
# Count Missing Values: You can count the number of missing values in each column using the isnull() method combined with the sum() method.
print(df1.isnull().sum())

print("\nRemoving Missing Values")
# You can remove rows with missing values using the dropna() method. By default, it removes any row that contains at least one missing value.
df1.dropna()

     Name  Age  Marks
0   Laksh   20   90.0
1   Aryan   21   85.0
2   Parth   22    NaN
3   Rohit   23   88.0
4   Rahul   24    NaN
5  Suresh   25   87.0

DataFrame with Missing Values:
    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False   True
3  False  False  False
4  False  False   True
5  False  False  False

Count of Missing Values in Each Column:
Name     0
Age      0
Marks    2
dtype: int64

Removing Missing Values

     Name  Age  Marks
0   Laksh   20   90.0
1   Aryan   21   85.0
3   Rohit   23   88.0
5  Suresh   25   87.0

In [115]:
print("\nFilling Missing Values")
# You can fill missing values with a specific value using the fillna() method. For example, to fill missing values in the "Marks" column with the mean of that column:
df1.fillna(0)

Filling Missing Values

     Name  Age  Marks
0   Laksh   20   90.0
1   Aryan   21   85.0
2   Parth   22    0.0
3   Rohit   23   88.0
4   Rahul   24    0.0
5  Suresh   25   87.0

In [132]:
# Saving DataFrame :You can save a DataFrame to a file using the to_csv() method for CSV files or to_excel() for Excel files.

# Save as CSV
df1.to_csv("example.csv", index=False)

# Save as Excel
df1.to_excel("example.xlsx", index=False)

In [133]:
# Reading Files
df2 = pd.read_csv("example.csv")
print(df2)

     Name  Age  Marks
0   Laksh   20   90.0
1   Aryan   21   85.0
2   Parth   22    NaN
3   Rohit   23   88.0
4   Rahul   24    NaN
5  Suresh   25   87.0

In [134]:
df2 = pd.read_excel("example.xlsx")
print(df2)

     Name  Age  Marks
0   Laksh   20   90.0
1   Aryan   21   85.0
2   Parth   22    NaN
3   Rohit   23   88.0
4   Rahul   24    NaN
5  Suresh   25   87.0